### ISSUE TITLE
Update Docs to Include Nodemon & Coffescript

### ISSUE THREAD

**Issue by schybo** [khaled/react-coffee-express-template#3]
Want to initially thank you for creating this button. Great stuff!

I usually use Heroku buttons to jumpstart learning new frameworks or pre-processors. In this case I didn't have `coffee-script` installed via `npm install -g coffee-script` and I ran into some confusing errors when I started Gulp. 

Do you mind adding a line to the docs that both `coffee-script` and `nodemon` need to be installed globally for this to work? It might save the next guy some time.

I'm happy to put in a PR if you're busy. But it might be easier for you to structure the placement. Just let me know. Thanks

**Comment by khaled** [comment]
@bscheibe You shouldn't need to have nodemon installed globally...
